### ISSUE TITLE
gcin 教學中沒有提到利用 gcin tools 對 gcin 設定，但資料夾中有其圖片

### ISSUE THREAD

**Issue by amoshyc** [henrybear327/Tutorial#7]
![圖片](https://github.com/henrybear327/Tutorial/blob/master/Assembly/gcin/picture/setting.png?raw=true)

教學中應加入這個，才能使人知道可以把不要的輸入法關掉、可以設定很多東西。

**Comment by henrybear327** [comment]
就直接加入吧~~

**Comment by henrybear327** [comment]
合作的目的就是如此
:)

**Comment by henrybear327** [comment]
該你下囉~~~
第一篇大家一起完成的文章
